### ISSUE TITLE
delete entry from database

### ISSUE THREAD

**Issue by royalterra** [jaywink/diaspora-hub#41]
Is there any correct system for delete a Pod from the mysql database I have 1 duplicate one row id is the domain.com the other is www.domain.com
Thanks in advance

**Comment by jaywink** [comment]
From which database, do you host your own diaspora-hub or did you mean the one running at the-federation.info?

**Comment by royalterra** [comment]
Hi Thanks @jaywink for reply I have one  diaspora-hub and I see duplicate entry's with https// and https:/www I look in the database and I am wondering how safely delete one from the database

**Comment by jaywink** [comment]
Well the real solution is to fix the bug that allows that (#22). Patches welcome! But yeah just delete the wrong one in the `pods` table and you'll be fine :)

I'm closing this here as a duplicate.
